"""user table

Revision ID: 4dc2a813daa9
Revises: 7513d91891c9
Create Date: 2024-05-05 22:30:49.718317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc2a813daa9'
down_revision = '7513d91891c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('postcode',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('postcode',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
