"""users table

Revision ID: 77157093d6fc
Revises: 4dc2a813daa9
Create Date: 2024-05-06 15:07:53.375899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77157093d6fc'
down_revision = '4dc2a813daa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_shop_name')
        batch_op.create_index(batch_op.f('ix_user_shop_name'), ['shop_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_shop_name'))
        batch_op.create_index('ix_user_shop_name', ['shop_name'], unique=1)

    # ### end Alembic commands ###
