"""split timestamp to created_on, modified_on

Revision ID: a69041ce11f1
Revises: 21c1be4351c2
Create Date: 2024-05-13 14:23:54.775228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69041ce11f1'
down_revision = '21c1be4351c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('modified_on', sa.DateTime(), nullable=False))
        batch_op.drop_index('ix_product_timestamp')
        batch_op.create_index(batch_op.f('ix_product_created_on'), ['created_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_modified_on'), ['modified_on'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_product_modified_on'))
        batch_op.drop_index(batch_op.f('ix_product_created_on'))
        batch_op.create_index('ix_product_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('modified_on')
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
