"""Image table new field

Revision ID: e735ee891fd0
Revises: b26a7ee34e41
Create Date: 2024-05-17 01:39:24.753897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e735ee891fd0'
down_revision = 'b26a7ee34e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_main', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('is_main')

    # ### end Alembic commands ###
