"""db cleaning

Revision ID: e8971b435682
Revises: a69041ce11f1
Create Date: 2024-05-14 04:35:40.608775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8971b435682'
down_revision = 'a69041ce11f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email_address', sa.String(length=120), nullable=False),
    sa.Column('postcode', sa.Integer(), nullable=False),
    sa.Column('contact_no', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(length=5000), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_created_on'), ['created_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_email_address'), ['email_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_condition'), ['condition'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_name'), ['product_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_quantity'), ['quantity'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_no', sa.String(), nullable=True))
        batch_op.alter_column('postcode',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('postcode',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('contact_no')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_quantity'))
        batch_op.drop_index(batch_op.f('ix_product_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_price'))
        batch_op.drop_index(batch_op.f('ix_product_location'))
        batch_op.drop_index(batch_op.f('ix_product_condition'))
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.drop_index(batch_op.f('ix_order_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_email_address'))
        batch_op.drop_index(batch_op.f('ix_order_created_on'))
        batch_op.drop_index(batch_op.f('ix_order_buyer_id'))

    op.drop_table('order')
    # ### end Alembic commands ###
