"""user

Revision ID: f082d5be112c
Revises: a4a7ab384a7a
Create Date: 2024-05-05 12:25:22.677380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f082d5be112c'
down_revision = 'a4a7ab384a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_address', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('postcode', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shop_name', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_email_address'), ['email_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_shop_name'), ['shop_name'], unique=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_shop_name'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_email_address'))
        batch_op.create_index('ix_user_email', ['email'], unique=1)
        batch_op.drop_column('shop_name')
        batch_op.drop_column('postcode')
        batch_op.drop_column('email_address')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_seller')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
